create extension if not exists pg_trgm;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,role text not null default 'customer' check(role in ('customer','admin')),created_at timestamptz not null default now());
create table if not exists public.categories(id uuid primary key default gen_random_uuid(),name text not null unique,slug text not null unique,description text,created_at timestamptz not null default now());
create table if not exists public.products(id uuid primary key default gen_random_uuid(),sku text not null unique,slug text not null unique,name text not null,description text,price numeric(12,2) not null check(price>=0),compare_at_price numeric(12,2),stock integer not null default 0 check(stock>=0),category_id uuid references public.categories(id) on delete set null,image_urls text[] not null default '{}',seo_title text,seo_description text,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists products_name_trgm on public.products using gin(name gin_trgm_ops);create index if not exists products_sku_trgm on public.products using gin(sku gin_trgm_ops);create index if not exists products_active_created on public.products(is_active,created_at desc);create index if not exists products_category on public.products(category_id,is_active);
create table if not exists public.store_settings(id boolean primary key default true,whatsapp_number text not null default '',whatsapp_template text not null default 'Hi Well Art Gallery! I want to buy: {product_name} | ID: {sku} | Price: ₹{price} | Link: {url}',site_name text not null default 'Well Art Gallery',seo_title text,seo_description text,updated_at timestamptz not null default now());
create table if not exists public.hero_banners(id uuid primary key default gen_random_uuid(),title text not null,subtitle text,image_url text not null,cta_text text default 'Shop Now',cta_url text default '/products',sort_order integer not null default 0,is_active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.audit_logs(id bigint generated always as identity primary key,actor uuid references auth.users(id) on delete set null,action text not null,entity_type text,entity_id text,metadata jsonb,created_at timestamptz not null default now());
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin'); $$;
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists products_updated_at on public.products;create trigger products_updated_at before update on public.products for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;alter table public.categories enable row level security;alter table public.products enable row level security;alter table public.store_settings enable row level security;alter table public.hero_banners enable row level security;alter table public.audit_logs enable row level security;
drop policy if exists "public categories read" on public.categories;create policy "public categories read" on public.categories for select using(true);
drop policy if exists "public active products read" on public.products;create policy "public active products read" on public.products for select using(is_active=true or public.is_admin());
drop policy if exists "admin products write" on public.products;create policy "admin products write" on public.products for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists "public banners read" on public.hero_banners;create policy "public banners read" on public.hero_banners for select using(is_active=true or public.is_admin());drop policy if exists "admin banners write" on public.hero_banners;create policy "admin banners write" on public.hero_banners for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists "public settings read" on public.store_settings;create policy "public settings read" on public.store_settings for select using(true);drop policy if exists "admin settings write" on public.store_settings;create policy "admin settings write" on public.store_settings for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists "admin audit read" on public.audit_logs;create policy "admin audit read" on public.audit_logs for select using(public.is_admin());drop policy if exists "admin audit insert" on public.audit_logs;create policy "admin audit insert" on public.audit_logs for insert with check(public.is_admin());
drop policy if exists "own profile" on public.profiles;create policy "own profile" on public.profiles for select using(id=auth.uid());

insert into public.store_settings(id) values(true) on conflict(id) do nothing;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id) values(new.id) on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
