'use client';
import {useEffect,useState} from 'react';import * as XLSX from 'xlsx';import {createClient} from '@/lib/supabase';import {LogOut,Upload,Package,Settings,Image as ImageIcon,FolderTree,Trash2,Save} from 'lucide-react';
const getSB=()=>createClient();
export default function AdminPage(){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[user,setUser]=useState<any>(null),[admin,setAdmin]=useState(false),[status,setStatus]=useState(''),[tab,setTab]=useState('Products');const [products,setProducts]=useState<any[]>([]),[categories,setCategories]=useState<any[]>([]),[banners,setBanners]=useState<any[]>([]),[settings,setSettings]=useState<any>({whatsapp_number:'',whatsapp_template:''});const [form,setForm]=useState({name:'',sku:'',price:'',stock:'0',category_id:'',description:'',image_urls:''});const [catName,setCatName]=useState(''),[banner,setBanner]=useState({title:'',subtitle:'',image_url:'',cta_text:'Shop Now',cta_url:'/products'});
 const refresh=async()=>{const sb=getSB();const [p,c,b,s]=await Promise.all([sb.from('products').select('id,sku,name,price,stock,is_active').order('created_at',{ascending:false}).limit(100),sb.from('categories').select('*').order('name'),sb.from('hero_banners').select('*').order('sort_order'),sb.from('store_settings').select('*').eq('id',true).maybeSingle()]);setProducts(p.data||[]);setCategories(c.data||[]);setBanners(b.data||[]);if(s.data)setSettings(s.data)};
 useEffect(()=>{const sb=getSB();sb.auth.getUser().then(async({data})=>{if(data.user){setUser(data.user);const r=await sb.from('profiles').select('role').eq('id',data.user.id).maybeSingle();setAdmin(r.data?.role==='admin');if(r.data?.role==='admin')refresh()}})},[]);
 const login=async()=>{const sb=getSB();setStatus('Signing in...');const {data,error}=await sb.auth.signInWithPassword({email,password});if(error){setStatus(error.message);return}setUser(data.user);const r=await sb.from('profiles').select('role').eq('id',data.user.id).maybeSingle();if(r.data?.role!=='admin'){await sb.auth.signOut();setUser(null);setStatus('This account is not an admin.');return}setAdmin(true);setStatus('Signed in');refresh()};
 const logout=async()=>{const sb=getSB();await sb.auth.signOut();setUser(null);setAdmin(false)};
 const addProduct=async()=>{const sb=getSB();setStatus('Saving...');const slug=form.sku.toLowerCase().replace(/[^a-z0-9]+/g,'-');const urls=form.image_urls.split(/\s*,\s*|\s+/).filter(Boolean);const {error}=await sb.from('products').insert({sku:form.sku.trim(),slug,name:form.name.trim(),price:Number(form.price),stock:Number(form.stock),category_id:form.category_id||null,description:form.description,image_urls:urls,is_active:true});setStatus(error?error.message:'Product saved');if(!error){setForm({name:'',sku:'',price:'',stock:'0',category_id:'',description:'',image_urls:''});refresh()}};
 const removeProduct=async(id:string)=>{const sb=getSB();if(!confirm('Delete this product?'))return;const {error}=await sb.from('products').delete().eq('id',id);setStatus(error?error.message:'Product deleted');refresh()};
 const addCategory=async()=>{const sb=getSB();const slug=catName.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-');const {error}=await sb.from('categories').insert({name:catName.trim(),slug});setStatus(error?error.message:'Category added');setCatName('');refresh()};
 const uploadImage=async(file:File,bucket:'product-images'|'hero-images')=>{const sb=getSB();const path=`${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const {error}=await sb.storage.from(bucket).upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;return sb.storage.from(bucket).getPublicUrl(path).data.publicUrl};
 const handleProductFile=async(file:File)=>{setStatus('Uploading image...');try{const url=await uploadImage(file,'product-images');setForm(x=>({...x,image_urls:x.image_urls?`${x.image_urls},${url}`:url}));setStatus('Image uploaded')}catch(e:any){setStatus(e.message)}};
 const handleBannerFile=async(file:File)=>{setStatus('Uploading banner...');try{const url=await uploadImage(file,'hero-images');setBanner(x=>({...x,image_url:url}));setStatus('Banner image uploaded')}catch(e:any){setStatus(e.message)}};
 const addBanner=async()=>{const sb=getSB();const {error}=await sb.from('hero_banners').insert({...banner,sort_order:banners.length,is_active:true});setStatus(error?error.message:'Banner added');if(!error){setBanner({title:'',subtitle:'',image_url:'',cta_text:'Shop Now',cta_url:'/products'});refresh()}};
 const saveSettings=async()=>{const sb=getSB();const {error}=await sb.from('store_settings').upsert({...settings,id:true});setStatus(error?error.message:'Settings saved');};
 const importSheet=async(file:File)=>{const sb=getSB();setStatus('Reading import file...');try{const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});const rows=XLSX.utils.sheet_to_json<any>(wb.Sheets[wb.SheetNames[0]],{defval:''});const payload=rows.slice(0,1000).map((r:any)=>({sku:String(r.sku||r.SKU||'').trim(),slug:String(r.slug||r.SKU||r.sku||r.name||'').toLowerCase().replace(/[^a-z0-9]+/g,'-'),name:String(r.name||r.Name||'').trim(),description:String(r.description||r.Description||''),price:Number(r.price||r.Price||0),compare_at_price:r.compare_at_price?Number(r.compare_at_price):null,stock:Number(r.stock||r.Stock||0),image_urls:String(r.image_urls||r.image||r.images||'').split(/\s*,\s*|\s+/).filter(Boolean),is_active:true})).filter((r:any)=>r.sku&&r.name&&Number.isFinite(r.price));if(!payload.length)throw new Error('No valid rows. Required: sku, name, price.');const {error}=await sb.from('products').upsert(payload,{onConflict:'sku'});setStatus(error?error.message:`Imported ${payload.length} products`);if(!error)refresh()}catch(e:any){setStatus(e.message)}};
 if(!process.env.NEXT_PUBLIC_SUPABASE_URL)return <main className="admin-page"><div className="admin-card"><h1>Well Art Gallery Admin</h1><p>Connect Supabase in <b>.env.local</b> first.</p></div></main>;
 if(!user||!admin)return <main className="admin-page"><div className="admin-card"><h1>Admin Login</h1><p className="muted">Only users with <b>admin</b> role can access the dashboard.</p><input className="admin-input" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input className="admin-input" placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="primary-btn full" onClick={login}>Login</button>{status&&<p className="status">{status}</p>}</div></main>;
 const tabs=[['Products',Package],['Banners',ImageIcon],['Categories',FolderTree],['Settings',Settings]];return <main className="admin-page"><div className="admin-wrap"><aside className="admin-side"><h2>Well Art</h2>{tabs.map(([x,I]:any)=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}><I/> {x}</button>)}<button onClick={logout}><LogOut/> Logout</button></aside><section className="admin-main"><div className="admin-head"><div><p className="eyebrow">Secure dashboard</p><h1>{tab}</h1></div><span className="status">{status||user.email}</span></div>
 {tab==='Products'&&<><div className="admin-card"><h3>Add product</h3><div className="admin-form wide"><input className="admin-input" placeholder="Product name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className="admin-input" placeholder="SKU" value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/><input className="admin-input" placeholder="Price" type="number" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><input className="admin-input" placeholder="Stock" type="number" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/><select className="admin-input" value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})}><option value="">Category</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><textarea className="admin-input" placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input className="admin-input" placeholder="Image URLs (comma separated)" value={form.image_urls} onChange={e=>setForm({...form,image_urls:e.target.value})}/><label className="upload-btn"><Upload/> Upload image<input hidden type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&handleProductFile(e.target.files[0])}/></label><button className="primary-btn" onClick={addProduct}><Save/> Save Product</button></div><hr/><p><b>Bulk import:</b> CSV/XLSX with <code>sku,name,price,stock,description,image_urls</code>.</p><input type="file" accept=".csv,.xlsx,.xls" onChange={e=>e.target.files?.[0]&&importSheet(e.target.files[0])}/></div><div className="admin-card"><h3>Products ({products.length})</h3>{products.map(p=><div className="admin-row" key={p.id}><span><b>{p.name}</b><small>{p.sku} · ₹{Number(p.price).toLocaleString('en-IN')} · Stock {p.stock}</small></span><button className="danger-btn" onClick={()=>removeProduct(p.id)}><Trash2/></button></div>)}</div></>}
 {tab==='Categories'&&<div className="admin-card"><h3>Categories</h3><div className="inline-form"><input className="admin-input" placeholder="New category" value={catName} onChange={e=>setCatName(e.target.value)}/><button className="primary-btn" onClick={addCategory}>Add</button></div>{categories.map(c=><div className="admin-row" key={c.id}><span>{c.name}<small>/{c.slug}</small></span></div>)}</div>}
 {tab==='Banners'&&<div className="admin-card"><h3>Add hero banner</h3><input className="admin-input" placeholder="Title" value={banner.title} onChange={e=>setBanner({...banner,title:e.target.value})}/><input className="admin-input" placeholder="Subtitle" value={banner.subtitle} onChange={e=>setBanner({...banner,subtitle:e.target.value})}/><input className="admin-input" placeholder="Image URL" value={banner.image_url} onChange={e=>setBanner({...banner,image_url:e.target.value})}/><label className="upload-btn"><Upload/> Upload banner<input hidden type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&handleBannerFile(e.target.files[0])}/></label><input className="admin-input" placeholder="Button text" value={banner.cta_text} onChange={e=>setBanner({...banner,cta_text:e.target.value})}/><input className="admin-input" placeholder="Button URL" value={banner.cta_url} onChange={e=>setBanner({...banner,cta_url:e.target.value})}/><button className="primary-btn" onClick={addBanner}>Save Banner</button>{banners.map(b=><div className="admin-row" key={b.id}><span><b>{b.title}</b><small>{b.image_url}</small></span></div>)}</div>}
 {tab==='Settings'&&<div className="admin-card"><h3>Store settings</h3><label>WhatsApp number<input className="admin-input" value={settings.whatsapp_number||''} onChange={e=>setSettings({...settings,whatsapp_number:e.target.value})}/></label><label>WhatsApp template<textarea className="admin-input" rows={5} value={settings.whatsapp_template||''} onChange={e=>setSettings({...settings,whatsapp_template:e.target.value})}/></label><label>SEO title<input className="admin-input" value={settings.seo_title||''} onChange={e=>setSettings({...settings,seo_title:e.target.value})}/></label><label>SEO description<textarea className="admin-input" value={settings.seo_description||''} onChange={e=>setSettings({...settings,seo_description:e.target.value})}/></label><button className="primary-btn" onClick={saveSettings}><Save/> Save Settings</button></div>}
 </section></div></main>}
